# =====================
# Autogoal base image
# ---------------------

FROM autogoal:base

EXPOSE 8000

COPY ./storage /home/coder/autogoal/storage

SHELL ["conda", "run", "-n", "autogoal", "/bin/bash", "-c"]

RUN sudo chmod +x ./storage/contribs.sh && sudo ./storage/contribs.sh

CMD [ "python3", "-m", "autogoal", "ml", "serve" ]
