# =====================
# Autogoal base image
# ---------------------

FROM autogoal/autogoal:core

USER root

ARG extras
RUN ./install-package.sh $extras

EXPOSE 8000

COPY ./storage /home/coder/autogoal/storage

SHELL ["conda", "run", "--live-stream", "-n", "autogoal", "/bin/bash", "-c"]

RUN chmod +x ./storage/contribs.sh && ./storage/contribs.sh

CMD [ "conda", "run", "--live-stream", "-n", "python3", "-m", "autogoal", "ml", "serve" ]
