# =====================
# Python 3.7 base image
# ---------------------

FROM python:3.9

# =====================
# Basic enviroment setup
# ---------------------

RUN apt update \
 && apt install -y \
    curl \
    locales \
    nano \
    ssh \
    sudo \
    bash \
    git \
    make \
    gcc \
    build-essential \ 
    python3-dev


# =====================
# User stuff
# ---------------------

# https://wiki.debian.org/Locale#Manually
RUN sed -i "s/# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen \
  && locale-gen
ENV LANG=en_US.UTF-8
RUN chsh -s /bin/bash
ENV SHELL=/bin/bash
RUN adduser --gecos '' --disabled-password coder && \
  echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd

# ==========================================
# Project-specific installation instruction
# ------------------------------------------

COPY bash.bashrc /etc
RUN chmod +x /etc/bash.bashrc
ENV BUILD_ENVIRONMENT="development"
ENV XDG_CACHE_HOME="/opt/dev/cache"
WORKDIR /home/coder/autogoal

# Make RUN commands use the autogoal environment
COPY pyproject.toml makefile /home/coder/autogoal/

# RUN poetry install
RUN pip install -U pip setuptools
RUN pip install poetry==1.2
RUN poetry config virtualenvs.create false
RUN poetry install

SHELL ["/bin/bash", "-c"]
USER coder
RUN sudo mkdir -p /home/coder/autogoal/data && sudo chown coder:coder /home/coder/autogoal
VOLUME /home/coder/autogoal
COPY ../autogoal /home/coder/autogoal
RUN sudo rm -rf /home/coder/autogoal/storage
RUN sudo ln -s /home/coder/autogoal/autogoal /usr/local/lib/python3.9/site-packages/autogoal
RUN sudo chown -R coder /home/coder

CMD ["/bin/bash"]

EXPOSE 8000-8010
EXPOSE 8501-8510
