# =====================
# Debian base image
# ---------------------

FROM tensorflow/tensorflow:latest-gpu-py3

RUN pip install -U pip
RUN pip install tensorflow_addons==0.9.1
RUN pip install torch torchvision


# =====================
# User stuff
# ---------------------

RUN apt-get update \
 && apt-get install -y \
    curl \
    locales \
    nano \
    ssh \
    sudo \
    bash \
    python3-pip

RUN rm -rf /var/lib/apt/lists/*

# https://wiki.debian.org/Locale#Manually
RUN sed -i "s/# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen \
  && locale-gen
ENV LANG=en_US.UTF-8

RUN chsh -s /bin/bash
ENV SHELL=/bin/bash

RUN adduser --gecos '' --disabled-password coder && \
  echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd

# ==========================================
# Project-specific installation instruction
# ------------------------------------------

COPY bash.bashrc /etc
RUN chmod +x /etc/bash.bashrc

ENV BUILD_ENVIRONMENT="development"
ENV XDG_CACHE_HOME="/opt/dev/cache"

WORKDIR /home/coder/autogoal

COPY pyproject.toml poetry.lock makefile /home/coder/autogoal/

RUN make env

RUN poetry install

CMD ["/bin/bash"]