FROM docker.uclv.cu/autogoal/autogoal

WORKDIR /home/coder/autogoal

RUN sudo apt update 
RUN pip install -U augly

COPY . /home/coder/autogoal/autogoal/expermiental/

CMD [ "python", "-m", "pytest", "autogoal/expermiental/augly/test_augly.py" ]
