
# =====================
# Autogoal production image
# ---------------------

FROM autogoal/autogoal:core

USER root

RUN ./install-package.sh common remote 

EXPOSE 8000

COPY ./storage /home/coder/autogoal/autogoal-export/storage

CMD ["python3", "-m", "autogoal", "remote", "serve" ]

