# =====================
# Autogoal base image
# ---------------------

FROM autogoal:conda_base

USER root

SHELL ["conda", "run", "-n", "autogoal", "/bin/bash", "-c"]

RUN conda install -y tensorflow-gpu==2.1.0 && pip install tensorflow-addons==0.9.1 torch==1.10.1 torchvision==0.11.2
RUN poetry install -E contrib

SHELL ["/bin/bash", "-c"]

USER coder

CMD [ "/bin/bash" ]
