# =====================
# Autogoal streamlit demo image
# ---------------------

FROM autogoal/autogoal:core

USER root

ARG extras

COPY dockerfiles/install-package.sh install-package.sh 
RUN ./install-package.sh common sklearn nltk remote streamlit

SHELL ["/bin/bash", "-c"]

USER coder

CMD ["python3", "-m", "autogoal", "streamlit", "demo" ]