# =====================
# Autogoal development image
# ---------------------

FROM autogoal/autogoal:core

USER root

ARG extras

COPY dockerfiles/install-package.sh install-package.sh 
RUN for arg in $extras; do sudo ./install-package.sh $arg; done

SHELL ["/bin/bash", "-c"]

USER coder

CMD [ "/bin/bash" ]

