# =====================
# Autogoal development image
# ---------------------

FROM autogoal/autogoal:core

USER root

ARG extras

COPY dockerfiles/install-package.sh install-package.sh 
RUN chmod +x install-package.sh
RUN ./install-package.sh $extras

SHELL ["/bin/bash", "-c"]

USER coder

CMD [ "/bin/bash" ]

