# =====================
# Autogoal development image
# ---------------------

FROM autogoal/autogoal:core

USER root

ARG extras

RUN ls -la /home/coder/autogoal/autogoal-remote/


SHELL ["/bin/bash", "-c"]

USER coder

CMD [ "/bin/bash" ]

